import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {href: '/', Label: 'Home'},
  {href: '/about', Label: 'About'},
  {href: '/presentation', Label: 'Presentation'},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='flex items-center'>
              {links.map((link) => (
                <li key = {link.href}>
                  <Link href={link.href}>{link.Label}</Link>
                </li>
              ))}

            </ul>
          </nav>
        </header>
        <h1>My Site</h1>
        <div>{children}</div>

      </body>
    </html>
  )
}
